name: Build and Deploy to Cloud Run

on:
  push:
    branches: [ main ]

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }} # Replace with your GCP project ID
  REGION: us-central1 # Replace with your desired region

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Login to Google Cloud
        uses: google/cloud-actions/setup-gcloud@v2
        with:
          service_account_key: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }} # Replace with your service account key

      - name: Build Docker image
        run: docker build -t gcr.io/$PROJECT_ID/kadecs_cms .

      - name: Authenticate Docker with Google Cloud
        run: gcloud auth configure-docker

      - name: Push Docker image to Google Cloud Registry
        run: docker push gcr.io/$PROJECT_ID/kadecs_cms:latest

      - name: Deploy to Cloud Run (using pre-built image)
        run: |
          gcloud run deploy flutter-endpoints \
            --image gcr.io/$PROJECT_ID/kadecs_cms:latest \
            --platform managed \
            --region $REGION \
            --allow-unauthenticated

