name: Build and Deploy to Cloud Run

on:
  push:
    branches: [ main ]

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }} # Replace with your GCP project ID
  REGION: us-central1 # Replace with your desired region

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
            credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
            service_account: '${{ secrets.GCP_SERVICE_ACCOUNT }}'


      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v2'
        with:
            version: '>= 363.0.0'

      - name: Build Docker image
        run: docker build -t gcr.io/${{ env.GCP_PROJECT }}/kadecs_cms:latest .

      - name: Authenticate Docker with Google Cloud
        run: gcloud auth configure-docker

      - name: Push Docker image to Google Cloud Registry
        run: docker push gcr.io/${{ env.GCP_PROJECT }}/kadecs_cms:latest

      - name: Update Cloud Run Secrets
        uses: actions/checkout@v3
      - name: Decode Secrets and Update Service
        run: |
          sh update_secrets.sh
        env:
          # Inherit all environment variables from the runner
          **
          
      - name: Deploy to Cloud Run (using pre-built image)
        run: |
          gcloud run deploy flutter-endpoints \
            --image gcr.io/${{ env.GCP_PROJECT }}/kadecs_cms:latest \
            --platform managed \
            --region europe-west1 \
            --allow-unauthenticated \
            --port 1337

